### PR TITLE
Change pd.read_table to pd.read_csv with sep='\t'.

### PR DESCRIPTION
**Pull request by haakonvt**
Reason: Deprecated since pandas version 0.24.0.

### CODE REVIEW

**Comment by haakonvt** [comment]
@kszucs

**Comment by amonsat** [comment]
why not merge this???

**Comment by haakonvt** [comment]
As of pandas version 0.25, `pd.read_table` is undeprecated...

**Comment by Chianghao** [comment]
why not merge this !!!

**Comment by kszucs** [comment]
Sorry, I have not seen the notifications.

**Review by kszucs — APPROVED** [review]

**Pull request merged**
